name: copernicus-training
channels:
  - conda-forge
dependencies:

  - python=3.11
  - jupyterlab
  - notebook<7

  - numpy
  - xarray
  - pandas
  - matplotlib
  - cartopy          
  - copernicusmarine 
  - h5py
  - scipy
