#!/bin/bash
set -euxo pipefail

# --- Download example data (optional but fine) ---
wget "https://atlas.mercator-ocean.fr/s/i76MKm9zbbkJNW4/download" -O cyclone.zip
mkdir -p essentials
bsdtar -xf cyclone.zip --strip-components=1 -C essentials
rm -f cyclone.zip

wget "https://atlas.mercator-ocean.fr/s/f7ZpzWgnASPMoWF/download" -O essentials-python-manipulation.zip
mkdir -p essentials-python-manipulation
bsdtar -xf essentials-python-manipulation.zip --strip-components=1 -C essentials-python-manipulation
rm -f essentials-python-manipulation.zip

# Install R packages from CRAN that are missing on conda
R -e "install.packages('ggquiver', repos = 'https://cloud.r-project.org')"


# --- Python kernel (optional; Binder will give you a Python kernel anyway) ---
python -m ipykernel install --user \
  --name "python-marine" \
  --display-name "Python - Copernicus Marine"

# --- R kernel ---
# The typical Binder way: install system-wide kernelspec so Jupyter can see it
R -e "IRkernel::installspec(user = FALSE, name = 'ir', displayname = 'R')"
