#!/bin/bash
set -euxo pipefail

wget "https://atlas.mercator-ocean.fr/s/4TtdZgi6xYTzK67/download" -O training-materials.zip
mkdir -p training_materials

bsdtar -xf training-materials.zip --strip-components=1 -C training_materials

rm -f training-materials.zip
