#!/bin/bash
set -euxo pipefail

wget "https://atlas.mercator-ocean.fr/s/ND6NnwjaHdb7sPB/download" -O training-materials.zip
mkdir -p Future_Of_The_High_Seas

# Extract only the two folders
bsdtar -xf training-materials.zip --strip-components=1 -C Future_Of_The_High_Seas "Python Tutorial"
bsdtar -xf training-materials.zip --strip-components=1 -C Future_Of_The_High_Seas "R Tutorial"

rm -f training-materials.zip

#R -e "install.packages('ggquiver', repos='https://cloud.r-project.org')"
